const ProductsData = [
  {
    id: 1,
    name: "Sepatu Kulit Asli Pengalengan",
    type: "kerajinan",
    price: "300000",
    description: "Sepatu kulit asli buatan tangan dari Pengalengan, nyaman dan tahan lama.",
    colourOptions: [
      { name: "Coklat", hex: "#8B4513" },
      { name: "Hitam", hex: "#000000" },
    ],
    sizeOptions: ["39", "40", "41", "42", "43"],
    flavourOptions: [],
    imageUrls: ["/product/SepatuKulit.svg", "/product/SepatuKulit.svg"],
    mainImage: "/product/SepatuKulit.svg",
    contactLink: "https://wa.me/6281234567890",
    diskon: true,
    presentaseDiskon: 20,
  },
  {
    id: 2,
    name: "Jaket Bomber",
    type: "kerajinan",
    price: "250000",
    description: "Jaket bomber modern dengan bahan parasut, cocok untuk gaya kasual.",
    colourOptions: [
      { name: "Hitam", hex: "#000000" },
      { name: "Hijau Army", hex: "#4B5320" },
      { name: "Navy", hex: "#000080" },
    ],
    sizeOptions: ["S", "M", "L", "XL"],
    flavourOptions: [],
    imageUrls: ["/product/JaketBomber.svg", "/product/JaketBomber.svg"],
    mainImage: "/product/JaketBomber.svg",
    contactLink: "https://wa.me/6281234567890",
    diskon: false,
  },
  {
    id: 3,
    name: "Keripik Pisang",
    type: "makanan",
    price: "30000",
    description: "Keripik pisang renyah dari pisang pilihan, cocok untuk camilan keluarga.",
    colourOptions: [],
    sizeOptions: ["100g", "250g"],
    flavourOptions: ["Original", "Coklat", "Keju", "Balado"],
    imageUrls: ["/product/KeripikPisang.svg"],
    mainImage: "/product/KeripikPisang.svg",
    contactLink: "https://wa.me/6281234567890",
    diskon: false,
  },
  {
    id: 4,
    name: "Perahu Mainan",
    type: "mainan",
    price: "10000",
    description: "Mainan perahu kecil dari kayu, cocok untuk anak-anak dan dekorasi.",
    colourOptions: [
      { name: "Merah", hex: "#FF0000" },
      { name: "Biru", hex: "#0000FF" },
      { name: "Kuning", hex: "#FFFF00" },
    ],
    sizeOptions: ["Kecil", "Sedang"],
    flavourOptions: [],
    imageUrls: ["/product/PerahuMainan.svg", "/product/PerahuMainan.svg", "/product/PerahuMainan.svg"],
    mainImage: "/product/PerahuMainan.svg",
    contactLink: "https://wa.me/6281234567890",
    diskon: false,
  },
  {
    id: 5,
    name: "Topi Pengalengan",
    type: "kerajinan",
    price: "50000",
    description: "Topi stylish buatan lokal dengan bordiran khas Pengalengan.",
    colourOptions: [
      { name: "Hitam", hex: "#000000" },
      { name: "Coklat", hex: "#8B4513" },
      { name: "Abu-Abu", hex: "#808080" },
    ],
    sizeOptions: ["All Size"],
    flavourOptions: [],
    imageUrls: ["/product/TopiPengalengan1.svg"],
    mainImage: "/product/TopiPengalengan.svg",
    contactLink: "https://wa.me/6281234567890",
    diskon: true,
    presentaseDiskon: 10,
  },
  {
    id: 6,
    name: "Sarung Tangan Kulit",
    type: "kerajinan",
    price: "75000",
    description: "Sarung tangan kulit asli untuk berkendara atau aktivitas outdoor.",
    colourOptions: [
      { name: "Hitam", hex: "#000000" },
      { name: "Coklat", hex: "#8B4513" },
    ],
    sizeOptions: ["M", "L", "XL"],
    flavourOptions: [],
    imageUrls: [],
    mainImage: "/product/SarungTangan.svg",
    contactLink: "https://wa.me/6281234567890",
    diskon: false,
  },
  {
    id: 7,
    name: "Permen Susu",
    type: "makanan",
    price: "35000",
    description: "Permen susu manis dan lembut dari susu segar Pengalengan.",
    flavourOptions: ["Original", "Strawberry", "Coklat"],
    colourOptions: [],
    sizeOptions: ["250g", "500g"],
    imageUrls: ["/product/PermenSusu.svg", "/product/PermenSusu.svg"],
    mainImage: "/product/PermenSusu.svg",
    contactLink: "https://wa.me/6281234567890",
    diskon: false,
  },
  {
    id: 8,
    name: "Dodol Susu",
    type: "makanan",
    price: "20000",
    description: "Dodol susu lembut dan legit dengan rasa manis khas susu segar.",
    colourOptions: [],
    sizeOptions: ["250g"],
    flavourOptions:  ["Original", "Pandan", "Durian"],
    imageUrls: ["/product/DodolSusu.svg", "/product/DodolSusu.svg", "/product/DodolSusu.svg",],
    mainImage: "/product/DodolSusu.svg",
    contactLink: "https://wa.me/6281234567890",
    diskon: false,
  },
  {
    id: 9,
    name: "Baju Batik",
    type: "kerajinan",
    price: "740000",
    description: "Kain batik khas dengan motif etnik yang elegan dan cocok digunakan dalam acara formal maupun santai.",
    colourOptions: [
      { name: "Biru", hex: "#1E90FF" },
      { name: "Coklat", hex: "#8B4513" },
      { name: "Hitam", hex: "#000000" },
      { name: "Merah", hex: "#B22222" },
      { name: "Putih", hex: "#FFFFFF" }
    ],
    sizeOptions: ["S", "M", "L", "XL"],
    flavourOptions: [],
    imageUrls: ["/product/bajuBatik.png", "/product/bajuBatik.png"],
    mainImage: "/product/bajuBatik.png",
    contactLink: "https://wa.me/6281234567890",
    diskon: true,
    presentaseDiskon: 10,
  },
  {
    id: 10,
    name: "Stroberi Pangalengan",
    type: "makanan",
    price: "57500",
    description: "Stroberi segar asli Pangalengan dengan rasa manis dan asam yang seimbang, cocok untuk camilan sehat atau bahan olahan.",
    flavourOptions: ["Manis", "Asam Segar", "Campuran"],
    sizeOptions: ["250g", "500g", "1kg"],
    colourOptions: [],
    imageUrls: [],
    mainImage: "/product/stroberiPangalengan.png",
    contactLink: "https://wa.me/6281234567890",
    diskon: false,
  },
  {
    id: 11,
    name: "Sayur Segar",
    type: "sayuran",
    price: "14700",
    description: "Paket sayur segar langsung dari kebun, terdiri dari berbagai jenis seperti tomat, wortel, selada, dan brokoli.",
    colourOptions: [],
    flavourOptions: [],
    sizeOptions: ["500g", "1kg", "1.5kg"],
    imageUrls: ["/product/sayurSegar.png", "/product/sayurSegar.png", "/product/sayurSegar.png"],
    mainImage: "/product/sayurSegar.png",
    contactLink: "https://wa.me/6281234567890",
  },
];

export default ProductsData;